### ISSUE TITLE
[BUG] Monk's Little details setting will not save to Monk's player settings

### ISSUE THREAD

**Issue by HavocsCall** [ironmonk88/monks-player-settings#12]
**Describe the bug**
Every time that I reload, it tries to set the Next Turn sound and Current turn sound to true. I have set this to false on multiple computers, in multiple worlds, many times each. It still tries to set it to true every time.

**To Reproduce**
1. First load into world
2. The window to Sync settings comes up asking to change those settings to true
3. I can say yes and then manually change it or click no and leave it
4. On reload, the window comes up and tries to sync again

**Expected behavior**
To save my new settings and not ask every time to sync back to the wrong setting

**Screenshots**
![image](https://user-images.githubusercontent.com/49051014/201488783-f00b87a6-af0e-4144-8dd2-383c9293d3de.png)

Manually changed it to false
![image](https://user-images.githubusercontent.com/49051014/201488799-87610562-3cf4-4fd6-80cb-036d8fc820f3.png)

It says updated user
![image](https://user-images.githubusercontent.com/49051014/201488834-5a337462-5f36-465d-81e1-4149cbcf62d6.png)
I am not sure where it saves the info, but I can get that screenshot once I know.

**Please complete as much of the following information as possible:**
 - Browser - Foundry Application and Chrome
 - Foundry Version - 10.288
 - System - DnD5e v2.0.3
 - Module version - 1.06
 - Are there any errors in the console [e.g. press F12 and look for red text] - No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. - Yes

**Additional context**
I love this issue template. Please make this a standard for all module authors.

**Comment by HavocsCall** [comment]
This seems to be happening with other module settings as well, so I think I might be doing something wrong. I will close and keep trying to figure it out.

**Comment by Elmaro** [comment]
Did this issue ever get solved? I still have it
