### ISSUE TITLE
[BUG] Some settings are not synced after updating to v10

### ISSUE THREAD

**Issue by Sinled** [ironmonk88/monks-player-settings#13]
**Describe the bug**
Stoped syncing some settings, e.g. turn sound from "Little details", 

**To Reproduce**
I am not sure how to make clean steps to reproduce, but 
all worked fine on v9
after updating foundry and all modules to v10
some settings are not synced

**Expected behavior**
Settings are correctly applied

**Screenshots**
<img width="419" alt="Screenshot 2022-12-16 at 10 53 46" src="https://user-images.githubusercontent.com/1402135/208060871-b28b6847-6eea-433b-9405-c4b4b88be6f6.png">

**Please complete as much of the following information as possible:**
 - Browsers Chrome, Firefox
 - Foundry v10
 - System: D&D5e
 - Module version - 1.0.6 (latest at the moment)
 - Are there any errors in the console - nothing related to this module
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. - core foundry settings synced without problems

**Comment by ironmonk88** [comment]
Closing this as the v10 version of this module is no longer supported and there's been enough changes in the meantime that most likely this has been fixed.
