### ISSUE TITLE
[BUG] Modifying a Player's Settings

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-player-settings#14]
Any settings modified by the GM aren't synced/saved to the player.

https://user-images.githubusercontent.com/99844555/210285252-3e08e76e-c58c-45e8-b1ae-bec84af9433d.mp4

Foundry 10.291
Player Settings 10.1

**Comment by ironmonk88** [comment]
Just adding an update that it's the core settings that aren't updating and I believe that was coded specifically into the module.
I believe that's a holdover from v9, need to investigate to see if these settings can be included.

**Comment by ironmonk88** [comment]
Fixed in the latest release
