### ISSUE TITLE
[BUG] Can't set player settings for core settings and PF2E Dorako Ui

### ISSUE THREAD

**Issue by XiaoKe89** [ironmonk88/monks-player-settings#15]
**Describe the bug**
Whenever I try to change the players settings, even after saving, the changes don't stick. When the player is logged out they don't get the sync box when logging in and when I try while they are logged in it gives the pop up message but the changes don't actually change even after refreshing

**To Reproduce**
1. Go to settings
2. change the user at the top
3. adjust settings
4. save
5. log in as player
6. check settings that should have changed

**Expected behavior**
The settings should change on the players end

**Please complete as much of the following information as possible:**
 - Browser: Chrome
 - Foundry Version: 10.291
 - System: Pathfinder 2e
 - Module version: 10.1
 - Are there any errors in the console [e.g. press F12 and look for red text] No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. Yes

**Additional context**
Core settings and PF2E Dorako Ui are the ones I can't adjust settings for. I was having some issues with a few other mods but then while testing they started working again. But while testing and using find the culprit the issue persists when doing core settings or PF2E Dorako ui

**Comment by ironmonk88** [comment]
Fixed in the latest release
