### ISSUE TITLE
[BUG] Some Settings Not Displaying Correctly to GM

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-player-settings#16]
Various modules.

PF2 Workbench
![image](https://github.com/ironmonk88/monks-player-settings/assets/99844555/febce53a-e88c-4ad5-a5af-756050191a05)

PF2 Dorako UI

![image](https://github.com/ironmonk88/monks-player-settings/assets/99844555/23a51913-7cc9-4181-9134-76517b161b9d)

TMFX

![image](https://github.com/ironmonk88/monks-player-settings/assets/99844555/5deeb82a-5bda-4abb-bf1d-aafdf9563a14)

FTC: Yes, besides these 3 modules that I left on to check the settings of. And Tagger, because I always forget to unlock it.
Player Settings 10.1

**Comment by ironmonk88** [comment]
Fixed in the latest release
