### ISSUE TITLE
Syncing Simple Calendar Settings

### ISSUE THREAD

**Issue by Gensokian** [ironmonk88/monks-player-settings#2]
MPS seems to be figuring out that some client settings have changed in the Simple Calendar module, at least on the client, but it doesn't sync them to the server and tries to load the old ones from the server when reloading

# Steps to reproduce
1. Load the modules
2. Open calendar
3. change settings
4. Reload page
5. See the changed settings applied
6. also notice the "Do you want to sync your client settings with the server settings" dialogue

Here's a gif showing the steps above plus the "sync" information from your module.
![saving](https://user-images.githubusercontent.com/9213561/167391264-aef52c06-5fe7-4af7-8cb2-ebc823d3154a.gif)

**Comment by Gensokian** [comment]
I am able to circumvent this by changing the clientsettings directly in the module settings manager;
I assume that Monk's Player Settings just doesn't update the server variables if the client (or A client) isn't clicking on "save changes" on the Module Settings Tab.

**Comment by ironmonk88** [comment]
Closing this as there's not much I can do about it.
The settings are only recognized as changing when done through the settings config.
There's too many to keep track of outside of the settings config to do it effectively.
