### ISSUE TITLE
[Compatibility] Force Client Settings by Kimitsu

### ISSUE THREAD

**Issue by Doresain** [ironmonk88/monks-player-settings#5]
Hey Monk, thanks for all your great modules man, they are killer.

This is just an FYI that this module unsurprisingly does not play nice with Kimitsu's 'Force Client Settings.' (https://gitlab.com/kimitsu_desu/force-client-settings) When forcing a setting via the latter app the settings window just closes without an error. I'm sure there are other issues too, but I didn't get that far.

It would be awesome if they played nice together so that one could use Kimitsu's module to force some settings (which removes them from players' settings menus altogether) and your module to set values that might be different from the GM.

Module compatibility is a bitch though so feel free to close if this feels outside the scope of what you want to do here. :)

**Comment by ironmonk88** [comment]
I'm guessing this has been fixed?  I've labeled it as fixed and there's a new release.
If this hasn't been fixed, please re-open.
