### ISSUE TITLE
Settings not syncing for Simple Calendar and Tidy5e Sheet

### ISSUE THREAD

**Issue by Avera9eJoe** [ironmonk88/monks-player-settings#9]
Greetings, when using Monk's Player Settings, my settings for Simple Calendar and Tidy5e Sheet are not synching; I.E. each time I join my world as one of the players both these modules have their default effects.

Intent: Make Simple Calendar and Tidy5e Sheet default to dark mode, and make Simple Calendar not open at start.
Issue: Neither options appear to save when logging into my world.

Steps to reproduce:
* Install Simple Calendar, TIdy5e Sheet, and Monk's Player Settings
* Enter world as DM
* Configure Settings:
     - Simple Calendar --> `Theme: Classic`, `Open on Load: Untick`
     - Tidy5e Sheet --> `Tidy5e color theme: Alternate (dark)`
* Save Changes
* Reload Application
* Login to world as another player via browser
* Note how none of these settings are applied to player character

**Comment by ironmonk88** [comment]
It's working for me.
You didn't mention it in your steps to reproduce... did you switch to the players settings when you made the changes?
![image](https://user-images.githubusercontent.com/75920956/205511067-f799514a-deb0-4bd1-b9ae-961e8945a279.png)

**Comment by ironmonk88** [comment]
Closing this as there's been no response to a question, and I'm unable to replicate.
